### PR TITLE
Fixes layout issue

### PR DESCRIPTION
**Pull request by reynoldtan**
This PR fixes layout issue described in issue #4 Layout Issue.

To Test:
1. Update sites/all/themes/kptheme
2. Switch branch to layout-issue
3. Clear caches and reload crops pages

### CODE REVIEW

**Comment by ruobinLiu** [comment]
All crop pages contain image in the right places 👍

**Review by laceysanderson — CHANGES_REQUESTED** [review]
Ooooh! Your change shows me why this broke! The width of 100% is needed for most bio data pages to keep the tables properly aligned -especially assembly pages. As you can see in [this page](http://knowpulse.usask.ca:8080/genomeassembly/2691107) the top table in overview is not the same width of the statistics table in overview... 
Screen Shot 2022-03-03 at 2 41 30 PM


For this fix you'll need to make an additional stanza specific to organism pages and also check all other content pages 😬

**Comment by reynoldtan** [comment]
tested on

- [x] Crops page
- [x] Germplasm page
- [x] Markers
- [x] Lentil traits

**Review by laceysanderson — APPROVED** [review]
Hmm... that's a new way to do it :-) I would have done a fully CSS solution but this works too 👍 I checked organism + assembly pages and they now look as expected.

**Pull request merged**
